services:
  # Application PostgreSQL Database
  app-postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "14093:5432"
    volumes:
      - app_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Keycloak PostgreSQL Database
  keycloak-postgres:
    image: postgres:17-alpine
    command:
      [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "14092:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Keycloak Server
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_PORT: 5432
      KC_BOOTSTRAP_ADMIN_USERNAME: keycloak
      KC_BOOTSTRAP_ADMIN_PASSWORD: keycloak
    ports:
      - "14082:8080"
    depends_on:
      - keycloak-postgres
    restart: unless-stopped
    command: start-dev
    networks:
      - app-network

volumes:
  app_postgres_data:
  keycloak_postgres_data:

networks:
  app-network:
    driver: bridge